name: iOS Release

on:
  push:
    branches:
      - main
    paths:
      - 'ios/**'
      - 'app.json'
      - 'package.json'

jobs:
  build-and-release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm install
          cd ios
          rm -rf Pods
          rm -rf Podfile.lock
          rm -rf ~/Library/Caches/CocoaPods
          pod cache clean --all
          pod deintegrate
          pod setup
          pod install --repo-update --verbose
          cd ..
          
      - name: Install Fastlane
        run: |
          sudo gem install fastlane
          
      - name: Configure Fastlane
        run: |
          cd ios
          mkdir -p fastlane
          cat > fastlane/Fastfile << EOF
          default_platform(:ios)
          
          platform :ios do
            desc "Build and upload to App Store"
            lane :release do
              update_code_signing_settings(
                use_automatic_signing: true,
                team_id: "Q834NS68MG",
                targets: ["SobAi"]
              )
              
              build_ios_app(
                workspace: "SobAi.xcworkspace",
                scheme: "SobAi",
                export_method: "app-store",
                export_options: {
                  method: "app-store",
                  teamID: "Q834NS68MG",
                  signingStyle: "automatic"
                }
              )
            end
          end
          EOF
          
          cat > fastlane/Appfile << EOF
          app_identifier("com.sobai.app")
          apple_id("your-apple-id@example.com")
          team_id("Q834NS68MG")
          EOF
          cd ..
          
      - name: Build iOS app with Fastlane
        env:
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        run: |
          cd ios
          fastlane release
          cd ..
          
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: SobAi.ipa
          path: ios/SobAi.ipa
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ios/SobAi.ipa
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 