name: iOS Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app
      
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install NPM dependencies
      run: |
        npm install -g expo-cli
        npm install
        
    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods
        cd ios
        pod install
        
    - name: Build iOS app
      run: |
        cd ios
        xcodebuild -workspace SobAi.xcworkspace -scheme SobAi -configuration Release -destination 'generic/platform=iOS' archive -archivePath $PWD/build/SobAi.xcarchive
        
    - name: Export IPA
      run: |
        cd ios
        xcodebuild -exportArchive -archivePath $PWD/build/SobAi.xcarchive -exportOptionsPlist exportOptions.plist -exportPath $PWD/build
        
    - name: Upload to App Store Connect
      uses: apple-actions/upload-testflight-build@v1
      with:
        app-path: ios/build/SobAi.ipa
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }} 