name: iOS Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install NPM dependencies
        run: |
          npm install
          npx expo install --fix
          
      - name: Install EAS CLI
        run: npm install -g eas-cli
        
      - name: Configure EAS
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          echo "Configuring EAS..."
          eas build:configure
          
      - name: Build iOS app
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas build --platform ios --non-interactive
        
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: SobAi.ipa
          path: build/ios/*.ipa