name: iOS Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install NPM dependencies
        run: |
          npm install
          npx expo install --fix
          
      - name: Install EAS CLI
        run: npm install -g eas-cli
        
      - name: Configure EAS
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "::error::EXPO_TOKEN secret is not set. Please follow these steps:"
            echo "1. Run 'eas login' locally to get your token"
            echo "2. Go to your GitHub repository settings"
            echo "3. Navigate to Secrets and variables > Actions"
            echo "4. Add a new secret named EXPO_TOKEN"
            echo "5. Paste your token as the value"
            echo "6. Save the secret"
            exit 1
          fi
          echo "EXPO_TOKEN=${{ secrets.EXPO_TOKEN }}" > .env
          eas login --token ${{ secrets.EXPO_TOKEN }}
          eas whoami
          
      - name: Build iOS app
        run: eas build --platform ios --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: SobAi.ipa
          path: build/ios/*.ipa