name: iOS Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install NPM dependencies
        run: |
          npm ci
          CI=1 npx expo install
          
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.0'
          bundler-cache: true
          
      - name: Install CocoaPods
        run: |
          gem install cocoapods
          pod setup
          
      - name: Clean CocoaPods cache
        run: |
          cd ios
          rm -rf Pods
          rm -f Podfile.lock
          
      - name: Install pods
        run: |
          cd ios
          pod install
        env:
          CI: true
          
      - name: Build iOS app
        run: |
          cd ios
          xcodebuild -workspace SobAi.xcworkspace -scheme SobAi -configuration Release -destination 'generic/platform=iOS' clean archive -archivePath build/SobAi.xcarchive
          
      - name: Export IPA
        run: |
          cd ios
          xcodebuild -exportArchive -archivePath build/SobAi.xcarchive -exportOptionsPlist exportOptions.plist -exportPath build
          
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: SobAi.ipa
          path: ios/build/SobAi.ipa
