name: iOS Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app
      
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install NPM dependencies
      run: |
        npm install
        npx expo install
        
    - name: Verify React Native installation
      run: |
        if [ ! -f "node_modules/react-native/package.json" ]; then
          echo "React Native package.json not found!"
          exit 1
        fi
        echo "React Native installation verified"
        
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true
        
    - name: Clean CocoaPods cache
      run: |
        cd ios
        rm -rf Pods
        rm -rf Podfile.lock
        
    - name: Install and Setup CocoaPods
      run: |
        gem install cocoapods
        cd ios
        pod install --repo-update
        
    - name: Build iOS app
      env:
        DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
      run: |
        cd ios
        xcodebuild -workspace SobAi.xcworkspace -scheme SobAi -configuration Release -destination 'generic/platform=iOS' archive -archivePath $PWD/build/SobAi.xcarchive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
        
    - name: Export IPA
      run: |
        cd ios
        xcodebuild -exportArchive -archivePath $PWD/build/SobAi.xcarchive -exportOptionsPlist exportOptions.plist -exportPath $PWD/build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
        
    - name: Upload to App Store Connect
      if: github.ref == 'refs/heads/main'
      uses: apple-actions/upload-testflight-build@v1
      with:
        app-path: ios/build/SobAi.ipa
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }} 