name: iOS Build

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    branches:
      - main
    paths:
      - 'ios/**'
      - 'src/**'
      - 'app.json'
      - 'package.json'

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        npm install
        cd ios && pod install && cd ..
    
    - name: Install Fastlane
      run: |
        sudo gem install fastlane
    
    - name: Run Fastlane
      env:
        APPLE_TEAM_ID: Q834NS68MG
      run: |
        cd ios
        fastlane beta
    
    - name: Upload IPA
      uses: actions/upload-artifact@v3
      with:
        name: SobAi.ipa
        path: ios/build/SobAi.ipa 