name: iOS Build

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    branches:
      - main
    paths:
      - 'ios/**'
      - 'src/**'
      - 'app.json'
      - 'package.json'
      - '.github/workflows/**'

jobs:
  build:
    name: Build iOS App
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true
    
    - name: Install dependencies
      run: |
        npm install
        cd ios
        bundle install
        pod install
        cd ..
    
    - name: Install Provisioning Profile
      env:
        PROVISIONING_PROFILE: ${{ secrets.PROVISIONING_PROFILE }}
      run: |
        # Create the directory if it doesn't exist
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        
        # Decode and save the profile
        echo "$PROVISIONING_PROFILE" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/SB_AI.mobileprovision
        
        # Set correct permissions
        chmod 644 ~/Library/MobileDevice/Provisioning\ Profiles/SB_AI.mobileprovision
        
        # Verify the profile was installed
        ls -la ~/Library/MobileDevice/Provisioning\ Profiles/
        security cms -D -i ~/Library/MobileDevice/Provisioning\ Profiles/SB_AI.mobileprovision
    
    - name: Build iOS app
      env:
        APPLE_TEAM_ID: Q834NS68MG
        PROVISIONING_PROFILE_SPECIFIER: SB_AI
        CODE_SIGN_IDENTITY: iPhone Distribution
      run: |
        cd ios
        bundle exec fastlane build
    
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: SobAi.ipa
        path: ios/SobAi.ipa
        retention-days: 5 