name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Configure EAS
        run: npx eas-cli@latest configure --token ${{ secrets.EXPO_TOKEN }}
        
      - name: Build with EAS
        run: npx eas-cli@latest build --platform ios --non-interactive --token ${{ secrets.EXPO_TOKEN }} 