name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          npm ci
          npx expo install --fix

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          cd ios && pod install && cd ..

      - name: Build iOS App
        if: github.ref == 'refs/heads/main'
        run: |
          cd ios
          xcodebuild -workspace SobAi.xcworkspace -scheme SobAi -configuration Release -destination 'generic/platform=iOS' -archivePath SobAi.xcarchive archive
          xcodebuild -exportArchive -archivePath SobAi.xcarchive -exportOptionsPlist exportOptions.plist -exportPath .
          cd ..

      - name: Build Android App
        if: github.ref == 'refs/heads/main'
        run: |
          cd android
          ./gradlew assembleRelease
          cd ..

      - name: Upload Build Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            ios/SobAi.ipa
            android/app/build/outputs/bundle/release/app-release.aab
          retention-days: 5