name: iOS Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    env:
      EAS_ACCESS_TOKEN: ${{ secrets.EAS_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install
          npx expo install --fix

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Build iOS App with EAS
        run: eas build --platform ios --non-interactive

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SobAi.ipa
          path: dist/*.ipa